name: Archaeological Site Detection

on:
  workflow_dispatch:
  push:
    branch:
      - main

jobs:
  detect-sites:
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v4
   
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
   
    - name: Install Dependencies
      run: |
        npm init -y
        npm install @google/earthengine-api
   
    - name: Setup Authentication
      run: |
        mkdir -p key
        echo '${{ secrets.EE_SERVICE_ACCOUNT_JSON }}' > key/gee-key.json

    - name: Create Runner Script
      run: |
        echo 'const ee = require("@google/earthengine-api");
        const fs = require("fs");
        
        // Read our credentials
        const privateKey = JSON.parse(fs.readFileSync("./key/gee-key.json", "utf8"));
        
        // Read our detection script
        const detectionScript = fs.readFileSync("./src/detection.js", "utf8");
        
        // Initialize Earth Engine
        ee.data.authenticateViaPrivateKey(
          privateKey,
          () => {
            console.log("Authentication successful");
            ee.initialize(
              null,
              null,
              () => {
                console.log("Earth Engine initialized");
                eval(detectionScript);
                console.log("Detection script started!");
              },
              (err) => {
                console.error("Error initializing Earth Engine:", err);
                process.exit(1);
              }
            );
          },
          (err) => {
            console.error("Error authenticating:", err);
            process.exit(1);
          }
        );' > runner.js
   
    - name: Run Detection
      run: node runner.js
   
    - name: Cleanup
      if: always()
      run: rm -rf key