name: Archaeological Site Detection

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  detect-sites:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: pip install earthengine-api
        
    - name: Setup Authentication
      run: |
        mkdir -p key
        echo '${{ secrets.EE_SERVICE_ACCOUNT_JSON }}' > key/gee-key.json
        python -c "
        import ee
        credentials = ee.ServiceAccountCredentials(
            'gee-archaeological-detection@ee-ekbrothers.iam.gserviceaccount.com', 
            'key/gee-key.json'
        )
        ee.Initialize(credentials)
        print('Successfully authenticated')
        "
        
    - name: Run detection script
      run: earthengine run src/detection.js

    - name: Cleanup
      if: always()
      run: rm -rf key