name: Archaeological Site Detection

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  detect-sites:
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v4
   
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
   
    - name: Install Earth Engine CLI
      run: |
        python -m pip install --upgrade pip
        pip install earthengine-api google-cloud-storage
   
    - name: Setup Authentication
      run: |
        mkdir -p key
        echo '${{ secrets.EE_SERVICE_ACCOUNT_JSON }}' > key/gee-key.json
        # Initialize Earth Engine with our service account
        python -c "
        import ee
        credentials = ee.ServiceAccountCredentials(
            'gee-archaeological-detection@ee-ekbrothers.iam.gserviceaccount.com',
            'key/gee-key.json'
        )
        ee.Initialize(credentials)
        "
   
    - name: Run detection script
      run: |
        earthengine --quiet run src/detection.js
   
    - name: Cleanup
      if: always()
      run: rm -rf key