name: Archaeological Site Detection

on:
  schedule:
    - cron: '0 0 1 * *'  # Run monthly
  workflow_dispatch:      # Allow manual triggers

jobs:
  detect-sites:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Earth Engine CLI
      run: |
        pip install earthengine-api
        
    - name: Setup Authentication
      run: |
        mkdir -p key
        echo '${{ secrets.EE_SERVICE_ACCOUNT_JSON }}' > key/gee-key.json
        # Verify the file exists and has content
        if [ ! -s key/gee-key.json ]; then
          echo "Error: Key file is empty or not created"
          exit 1
        fi
        earthengine authenticate --service-account --key-file key/gee-key.json

    - name: Run detection script
      run: |
        earthengine run src/detection.js
        
    - name: Cleanup credentials
      if: always()
      run: |
        rm -f key/gee-key.json
        rm -rf key