name: Archaeological Site Detection

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  detect-sites:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
        
    - name: Setup Authentication
      run: |
        mkdir -p key
        echo '${{ secrets.EE_SERVICE_ACCOUNT_JSON }}' > key/gee-key.json
        gcloud auth activate-service-account --key-file=key/gee-key.json
        
    - name: Run detection script
      run: |
        gcloud alpha earthengine scripts run src/detection.js
        
    - name: Cleanup
      if: always()
      run: rm -rf key