name: Archaeological Site Detection

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  push:
    branch:
      - main

jobs:
  detect-sites:
    runs-on: ubuntu-latest
   
    steps:
    # First, get our code from the repository
    - uses: actions/checkout@v4
   
    # Install the Google Cloud SDK which includes Earth Engine tools
    - name: Install Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        install_components: 'earthengine-python'  # Make sure we get Earth Engine components
   
    # Set up authentication using our service account
    - name: Setup Authentication
      run: |
        # Create a directory for our key if it doesn't exist
        mkdir -p key
        # Decode our service account JSON from GitHub secrets
        echo '${{ secrets.EE_SERVICE_ACCOUNT_JSON }}' > key/gee-key.json
        # Authenticate to Google Cloud with our service account
        gcloud auth activate-service-account --key-file=key/gee-key.json
        # Initialize Earth Engine with the same credentials
        earthengine authenticate --key-file key/gee-key.json
   
    # Run our detection script using Earth Engine
    - name: Run detection script
      run: |
        # Use the earthengine CLI to run our JavaScript
        earthengine --quiet run src/detection.js
   
    # Clean up our credentials securely
    - name: Cleanup
      if: always()  # Run even if previous steps fail
      run: rm -rf key